name: A workflow for my Hello World file
on: push
jobs:
    build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: ./action-a
        with:
            MY_NAME: "Miyuru"
            on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
